# Generated by Django 3.2 on 2021-04-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210426_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy_product',
            name='allergy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.allergy'),
        ),
    ]
